# Core variables shared by the rest of the config.

set $mod Mod4
set $alt Mod1

set $term wezterm
set $menu rofi -modi drun -show drun -config ~/.config/rofi/rofidmenu.rasi
set $window_menu rofi -show window -config ~/.config/rofi/rofidmenu.rasi
set $file_manager $HOME/Development/dotfiles/_bin/fm

# Adjust these if your output names change.
set $monitor_main HDMI-0
# set $monitor_secondary DP-0
# set $monitor_builtin eDP-1

set $ws1 "1:"
set $ws2 "2:"
set $ws3 "3:󰓓"
set $ws4 "4:"
set $ws5 "5:"
set $ws6 "6:"
set $ws7 "7:"
set $ws8 "8:"
set $ws9 "9:"

set $darkbluetrans  #08052be6
set $darkblue       #08052b
set $lightblue      #5294e2
set $urgentred      #e53935
set $white          #ffffff
set $black          #000000
set $purple         #e345ff
set $darkgrey       #383c4a
set $grey           #b0b5bd
set $mediumgrey     #8b8b8b
set $yellowbrown    #e1b700
