# EndeavourOS-inspired appearance and window rules.

font pango: Noto Sans Regular 10, RecMonoLinear Nerd Font Mono 10

workspace_layout default

new_window pixel 1
default_border pixel 1
default_floating_border pixel 1

gaps inner 6
gaps outer 3

floating_modifier $mod
focus_follows_mouse no
mouse_warping none

client.focused              $lightblue  $darkblue   $white      $mediumgrey $mediumgrey
client.unfocused            $darkblue   $darkblue   $grey       $darkgrey   $darkgrey
client.focused_inactive     $darkblue   $darkblue   $grey       $black      $black
client.urgent               $urgentred  $urgentred  $white      $yellowbrown $yellowbrown

for_window [class="Yad" instance="yad"] floating enable
for_window [class="Galculator" instance="galculator"] floating enable
for_window [class="Blueberry.py" instance="blueberry.py"] floating enable
for_window [class="Xsane" instance="xsane"] floating enable
for_window [class="Pavucontrol" instance="pavucontrol"] floating enable
for_window [class="qt5ct" instance="qt5ct"] floating enable
for_window [class="Bluetooth-sendto" instance="bluetooth-sendto"] floating enable
for_window [class="Pamac-manager"] floating enable
for_window [window_role="About"] floating enable

bar {
    font pango: Noto Sans Regular 10, RecMonoLinear Nerd Font Mono 10
    status_command i3blocks -c ~/.config/i3/i3blocks.conf
    position bottom
    tray_padding 0
    strip_workspace_numbers yes

    colors {
        separator          $purple
        background         $darkgrey
        statusline         $white
        focused_workspace  $mediumgrey $grey       $darkgrey $purple
        active_workspace   $lightblue  $mediumgrey $darkgrey $purple
        inactive_workspace $darkgrey   $darkgrey   $grey     $purple
        urgent_workspace   $urgentred  $urgentred  $white    $purple
    }
}
