# Workspace names and app placement.

assign [class="(?i)firefox"] $ws8
assign [class="(?i)discord"] $ws2
assign [class="file-manager"] $ws1
assign [class="(?i)steam"] $ws3
assign [class="github-pwa"] $ws4
assign [class="TelegramDesktop"] $ws6
assign [class="youtube"] $ws5
assign [class="youtube-music"] $ws5
assign [class="org.wezfurlong.wezterm"] $ws7
assign [class="Godot"] $ws9

for_window [class="(?i)firefox"] focus
for_window [class="(?i)discord"] focus
for_window [class="file-manager"] focus
for_window [class="(?i)steam"] focus
for_window [class="github-pwa"] focus
for_window [class="Thunderbird"] focus
for_window [class="TelegramDesktop"] focus
for_window [class="youtube"] focus
for_window [class="youtube-music"] focus
for_window [class="org.wezfurlong.wezterm"] focus
for_window [class="Godot"] focus
